var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                               x",
   "x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x",
   "x x                                                                           x x",
   "x x                                                                           x x",
   "x x                                                                      o    x x",
   "x x                              oo                                      xxxxxx x",
   "x x                            xxxxxx                                      vv x x",
   "x x                         x                                            o    x x",
   "x x                                                                      x    x x",
   "x x                       x                                                   x x",
   "x x                                                                      o    x x",
   "x x                     x              o                                 x    x x",
   "x x                                  xxxxx                                    x x",
   "x x    pp           xxxx             |   |         ss                    o    x x",
   "x x                 ovvo                         xxxxxx                  x    x x",
   "x x                                                xx                         x x",
   "x x             xxxx    xxxx                       xx                    o    x x",
   "x x            xx!!!!!!!!!!xx                x xx  xx  xx x              x    x x",
   "x x@   ss     xxx!!x!!!!x!!xxx o        xx xx!!!!!!xx!!!!!!xx xx  l l l  x oo x x",
   "x xxxxxxxxxxxxxxx!!xxxxxx!!xxxxxxxxxxxxx!!!!!!!!!!!xx!!!!!!!!!!!xxxxxxxxxxx  xx x",
   "x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xx x",
   "x                                                                            xx x",
   "xdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  [" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "       |                                                                                          |        ",
   "            p                                   |       |                                    p             ",
   "            xxxx     xxxx     xxxx                  o                   xxxx     xxxx     xxxx             ",
   "                                                                                                           ",
   " d                                                 sss                                                   d ",
   "                xxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxx                 ",
   "                |   |                           |       |                            |   |                 ",
   "                      o        o                                          o        o                       ",
   " x          l                                                                                l           x ",
   "            xxxx              xxxx                  o                   xxxx              xxxx             ",
   "                                                                                                           ",
   "                                                   sss                                                    ",
   " x     xxxxx    xxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxx    xxxxx      x ",
   "       |                                                                                          |        ",
   "             o        o        o                    o                     o        o        o              ",
   "            xxxx     xxxx     xxxx                                      xxxx     xxxx     xxxx             ",
   "            |                                                                                |             ",
   " x              s   s    s   s                  |   @   |                   s   s    s   s               x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x             x  ||          ||                        ||  ||     || |   |  |                ||    |  |  | |  |               |  |  | |                         |   | |        x            x",
   "x ppppppppppp x                                                                                                                                                                x     dd     x",
   "x             x                                                                                                                                                                x            x",
   "x             x                                 s                                                                                         ss       ss                          x            x",
   "x@                    sss            ||        sxs       ||            ||     |  ss  ss  ss         ||       |  ssss  ssss     |     |   sxx       xxs     |                                x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                      ",
   " x     x xxxxxxxxx x       x   x       x x xx     x x ",
   " x     x x       x x       x   x       x   xx     x x ",
   "  x   x  x       x x       x   x       x x x x    x x ",
   "   x x   x       x x       x   x       x x x  x   x x ",
   "    x    x       x x       x   x   x   x x x   x  x x ",
   "    x    x       x x       x   x   x   x x x    x x x ",
   "    x    x       x x   @   x   x   x   x x x     xx   ",
   "    x    xxxxxxxxx xxxxxxxxx   xxxxxxxxx x x     xx x ",
   "                                                      "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
